version: "1.1"

pipeline:
  name: bodywork-serve-model
  docker_image: bodyworkml/bodywork-core:latest
  DAG: popularity_service

stages:
  popularity_service:
    executable_module_path: popularity_service/service.py
    requirements:
      - Flask==2.0.3
      - joblib==1.1.0
      - numpy==1.22.3
    cpu_request: 0.5
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 30
      replicas: 1
      port: 5000
      ingress: true

logging:
  log_level: INFO
